name: Publish Rules

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish Rules
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install rules-cli
        run: npm install -g rules-cli
          
      - name: Publish to registry
        run: rules publish